### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by dsernst** [Boundless-Avocado/Boundless-Avocado#12]
Placeholder thread for deployment:
- which provider? Azure, Heroku, AWS, Digital Ocean, etc

**Comment by dsernst** [comment]
So @delucco @p3tuh , did we come to agreement that we wanted to use AWS for this?

**Comment by p3tuh** [comment]
AWS sounds great to me.

**Comment by dsernst** [comment]
Mike is taking over Deployment

**Comment by delucco** [comment]
Hey team, I went with Azure since we are up against a deadline and I wanted to limit the number of new technologies we are using. That being said, Azure is not playing well with node. See the following error: 

remote: Missing server.js/app.js files, web.config is not generated
remote: 
remote: > bcrypt@0.8.1 install D:\home\site\wwwroot\node_modules\bcrypt
remote: > node-gyp rebuild
remote: 
remote: 
remote: D:\home\site\wwwroot\node_modules\bcrypt>node "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild 
remote: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
remote: MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\home\site\wwwroot\node_modules\bcrypt\build\binding.sln]
remote: 
remote: npm ERR! bcrypt@0.8.1 install: `node-gyp rebuild`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the bcrypt@0.8.1 install script.
remote: npm ERR! This is most likely a problem with the bcrypt package,
remote: npm ERR! not with npm itself.
remote: npm ERR! Tell the author that this fails on your system:
remote: npm ERR!     node-gyp rebuild
remote: npm ERR! You can get their info via:
remote: npm ERR!     npm owner ls bcrypt
remote: npm ERR! There is likely additional logging output above.
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\Program Files (x86)\nodejs\0.10.32\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v0.10.32
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\0.10.32\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" install --productio
remote: npm ERR! npm -v 1.4.28
remote: An error has occurred during web site deployment.
remote: npm ERR! code ELIFECYCLE
remote: npm
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.

**Comment by dsernst** [comment]
Mike successfully deployed on http://avocados.azurewebsites.net/
